#!/usr/bin/env python3
"""Curate a client's accessorial vocabulary overlay from real invoices (PROMPTS #4).

Installed as the ``freight-audit-vocab`` console script:

    freight-audit-vocab suggest descriptions.json -o overlay.json
    freight-audit-vocab suggest loads.json --overlay-in existing.json -o overlay.json

Input may be a JSON list of line descriptions, a list of load bundles (invoice
line descriptions are pulled out), or {"descriptions": [...]}. It runs the vocab
learning loop (Vocabulary.suggest_unmatched), files each unmatched description
under its best-guess category as a trigger substring, and writes a starter overlay
for a human to review. The shipped vocab/accessorials.json is never modified.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict

from . import Vocabulary


def _descriptions(data) -> list[str]:
    out: list[str] = []
    for item in (data if isinstance(data, list) else [data]):
        if isinstance(item, str):
            out.append(item)
        elif isinstance(item, dict):
            if isinstance(item.get("descriptions"), list):
                out.extend(str(x) for x in item["descriptions"])
            inv = item.get("invoice") if isinstance(item.get("invoice"), dict) else item
            for li in (inv.get("line_items") or []):
                if isinstance(li, dict) and li.get("description"):
                    out.append(str(li["description"]))
    return out


def _suggest(args) -> int:
    data = json.load(open(args.input))
    descriptions = _descriptions(data)
    if not descriptions:
        print("no descriptions found in input", file=sys.stderr)
        return 1

    vocab = (Vocabulary.load(client_overlay=args.overlay_in)
             if args.overlay_in else Vocabulary.load())
    grouped: dict[str, list[str]] = defaultdict(list)
    review: list[str] = []
    seen: set[str] = set()
    for s in vocab.suggest_unmatched(descriptions):
        desc = s["description"]
        if desc in seen:
            continue
        seen.add(desc)
        if s["guess"] != "other":
            grouped[s["guess"]].append(desc)
        else:
            review.append(desc)

    overlay = {
        "_comment": ("GENERATED by `freight-audit-vocab suggest` -- REVIEW before use. "
                     "Each description is filed under its best-guess category as a trigger "
                     "substring; trim/correct, then load via "
                     "Vocabulary.load(client_overlay=...)."),
        "categories": {cat: sorted(set(v)) for cat, v in sorted(grouped.items())},
    }
    if review:
        overlay["_unmatched_review"] = sorted(set(review))

    out_path = args.output or "vocab_overlay.json"
    with open(out_path, "w") as fh:
        json.dump(overlay, fh, indent=2)

    n_terms = sum(len(v) for v in overlay["categories"].values())
    n_cats = len(overlay["categories"])
    msg = f"suggested {n_terms} term(s) across {n_cats} categor(ies) -> {out_path}"
    if review:
        msg += f"  ({len(review)} need manual review)"
    print(msg)
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="freight-audit-vocab", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sp = sub.add_parser("suggest", help="suggest an overlay from real invoice descriptions")
    sp.add_argument("input", help="JSON: descriptions list, load bundles, or {descriptions:[...]}")
    sp.add_argument("-o", "--output", help="overlay output path (default: vocab_overlay.json)")
    sp.add_argument("--overlay-in", help="existing overlay to extend (curated terms are skipped)")
    sp.set_defaults(func=_suggest)
    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
